openapi: 3.0.3
info:
  contact:
    email: yann.prono@telecomnancy.net
  description: Public API for Streamlabs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Streamlabs
  version: 1.0.0
servers:
  - description: OpenAPI definitions of Streamlabs API
    url: https://streamlabs.com/api/v1.0
tags:
  - name: alert profiles
    description: Find out more about alert profiles
  - name: alerts
  - name: authentication
  - name: credits
  - name: donations
  - name: jar
    description: Everything about jar
  - name: media share
  - name: other
  - name: points
  - name: sockets
  - name: users
  - name: wheel
    description: Find out more about wheel
paths:
  /authorize:
    get:
      description:
        In order to acquire an `access_token` for a user, you'll need to
        send them to this endpoint in order to approve your application. Learn more
        about connecting to an account here.
      operationId: Authorize
      tags:
        - authentication
  /token:
    post:
      description:
        Once a user has given approval from the /authorize endpoint, use
        this endpoint to receive an `access_token`.
      operationId: Token
      tags:
        - authentication
  /user:
    get:
      description:
        Fetch donations for the authenticated user. Results are ordered
        by creation date, descending.
      operationId: getUser
      security:
        - oauth2: []
      tags:
        - users
  /donations:
    get:
      description: Retrieve the list of donations
      operationId: getDonations
      security:
        - oauth2:
            - donations.read
      tags:
        - donations
    post:
      description: Create a donation for the authenticated user.
      operationId: CreateDonation
      security:
        - oauth2:
            - donations.create
      tags:
        - donations
  /alerts:
    post:
      description: Trigger a custom alert for the authenticated user.
      operationId: TriggerAlert
      security:
        - oauth2:
            - alerts.create
      tags:
        - alerts
  /alerts/skip:
    post:
      description: skip alerts
      operationId: SkipAlerts
      security:
        - oauth2:
            - alerts.write
      tags:
        - alerts
  /alerts/mute_volume:
    post:
      description: Mute volume
      operationId: MuteVolume
      security:
        - oauth2:
            - alerts.write
      tags:
        - alerts
  /alerts/unmute_volume:
    post:
      description: Unmute volume
      operationId: UnmuteVolume
      security:
        - oauth2:
            - alerts.write
      tags:
        - alerts
  /alerts/pause_queue:
    post:
      description: Pause alerts
      operationId: PauseAlerts
      security:
        - oauth2:
            - alerts.write
      tags:
        - alerts
  /alerts/unpause_queue:
    post:
      description: Unpause alerts
      operationId: UnpauseAlerts
      security:
        - oauth2:
            - alerts.write
      tags:
        - alerts
  /alerts/send_test_alert:
    post:
      description: Unpause alerts
      operationId: SendTestAlert
      security:
        - oauth2:
            - alerts.write
      tags:
        - alerts
  /alerts/show_video:
    post:
      description: show media sharing video
      operationId: ShowVideo
      security:
        - oauth2:
            - alerts.write
      tags:
        - alerts
  /alerts/hide_video:
    post:
      description: hide media sharing video
      operationId: HideVideo
      security:
        - oauth2:
            - alerts.write
      tags:
        - alerts
  /socket/token:
    get:
      description:
        Allows you to obtain a token which can be used to listen to user's
        event through sockets.
      operationId: SocketToken
      security:
        - oauth2:
            - socket.token
      tags:
        - sockets
  /legacy/token:
    get:
      description:
        Allows you to obtain a users legacy Streamlabs token which can
        be used in widget URLs.
      operationId: LegacySocketToken
      security:
        - oauth2:
            - legacy.token
      tags:
        - other
  /points:
    get:
      description: Get the number of points of the username
      operationId: GetPoints
      security:
        - oauth2:
            - points.read
      tags:
        - points
  /points/subtract:
    post:
      description: Subtract user's loyalty points
      operationId: SubtractPoints
      security:
        - oauth2:
            - points.write
      tags:
        - points
  /points/import:
    post:
      description: mass add points to users
      operationId: ImportPoints
      security:
        - oauth2:
            - points.write
      tags:
        - points
  /points/add_to_all:
    post:
      description: Add points to all users in the channel
      operationId: AddToAll
      security:
        - oauth2:
            - points.write
      tags:
        - points
  /points/user_point_edit:
    post:
      description: Edit points by username in a given channel
      operationId: EditUserPoints
      security:
        - oauth2:
            - points.write
      tags:
        - points
  /points/group_get_points:
    post:
      description: batch get points
      operationId: BatchGetPoints
      tags:
        - points
  /points/group_subtract_points:
    post:
      description: batch subtract points
      operationId: BatchSubstractPoints
      security:
        - oauth2:
            - points.write
      tags:
        - points
  /points/user_points:
    get:
      description:
        grab a 100 users sort by points/time_watched; search query based
        on a partial name
      operationId: GetUserPoints
      security:
        - oauth2: []
      tags:
        - points
  /points/reset:
    post:
      description: reset points of all users in the channel
      operationId: ResetPoints
      security:
        - oauth2: []
      tags:
        - points
  /alert_profiles/get:
    get:
      description: roll credits
      operationId: GetAlertProfiles
      security:
        - oauth2:
            - profiles.write
      tags:
        - alert profiles
  /alert_profiles/activate:
    post:
      description: Activate an alert profile
      operationId: ActivateAlertProfiles
      security:
        - oauth2:
            - profiles.write
      tags:
        - alert profiles
  /credits/roll:
    post:
      description: roll credits
      operationId: RollCredits
      security:
        - oauth2:
            - credits.write
      tags:
        - credits
  /jar/empty:
    post:
      description: empty jar
      operationId: EmptyJar
      security:
        - oauth2:
            - jar.write
      tags:
        - jar
  /wheel/spin:
    post:
      description: spin the wheel
      operationId: SpinWheel
      security:
        - oauth2:
            - wheel.write
      tags:
        - wheel
  /media-share/play-media:
    put:
      description: Play the media on the media share widget
      operationId: PlayMedia
      security:
        - oauth2:
            - mediashare.control
      tags:
        - media share
  /media-share/pause-media:
    put:
      description: Pause the media on the media share widget
      operationId: PauseMedia
      security:
        - oauth2:
            - mediashare.control
      tags:
        - media share
  /media-share/volume-up:
    put:
      description: Increase the volume of the media share widget by 1
      operationId: VolumeUp
      security:
        - oauth2:
            - mediashare.control
      tags:
        - media share
  /media-share/volume-down:
    put:
      description: Decrease the volume of the media share widget by 1
      operationId: VolumeDown
      security:
        - oauth2:
            - mediashare.control
      tags:
        - media share
  /media-share/skip-video:
    put:
      description: Skip to next video
      operationId: SkipVideo
      security:
        - oauth2:
            - mediashare.control
      tags:
        - media share
  /media-share/playback-video:
    put:
      description:
        Seek the time to 0 on current video otherwise play the previous
        video
      operationId: PlaybackVideo
      security:
        - oauth2:
            - mediashare.control
      tags:
        - media share
  /media-share/enable-requests:
    patch:
      description: Enable requests to accept new media
      operationId: EnableRequests
      security:
        - oauth2:
            - mediashare.control
      tags:
        - media share
  /media-share/disable-requests:
    patch:
      description: Disable requests to accept new media
      operationId: DisableRequests
      security:
        - oauth2:
            - mediashare.control
      tags:
        - media share
  /media-share/enable-autoshow:
    patch:
      description: Enable auto show for playing media
      operationId: EnableAutoshow
      security:
        - oauth2:
            - mediashare.control
      tags:
        - media share
  /media-share/disable-autoshow:
    patch:
      description: Disable auto show for playing media
      operationId: DisableAutoshow
      security:
        - oauth2:
            - mediashare.control
      tags:
        - media share
  /media-share/enable-autoplay:
    patch:
      description: Enable autoplay for queued media
      operationId: EnableAutoplay
      security:
        - oauth2:
            - mediashare.control
      tags:
        - media share
  /media-share/disable-autoplay:
    patch:
      description: Disable autoplay for queued media
      operationId: DisableAutoplay
      security:
        - oauth2:
            - mediashare.control
      tags:
        - media share
  /media-share/enable-moderation:
    patch:
      description: Enable moderation for incoming media
      operationId: EnableModeration
      security:
        - oauth2:
            - mediashare.control
      tags:
        - media share
  /media-share/disable-moderation:
    patch:
      description: Disable moderation for incoming media
      operationId: DisableModeration
      security:
        - oauth2:
            - mediashare.control
      tags:
        - media share
  /media-share/enable-backup-playlist:
    patch:
      description: Enable playing from backup playlist
      operationId: EnableBackupPlaylist
      security:
        - oauth2:
            - mediashare.control
      tags:
        - media share
  /media-share/disable-backup-playlist:
    patch:
      description: Disable playing from backup playlist
      operationId: DisableBackupPlaylist
      security:
        - oauth2:
            - mediashare.control
      tags:
        - media share
components:
  securitySchemes:
    oauth2:
      description: This API uses OAuth 2 with the implicit grant flow. [More info](https://dev.streamlabs.com/docs/oauth-2)
      flows:
        authorizationCode:
          authorizationUrl: /api/v1.0/authorize?grant_type=grant_type
          scopes:
            donations.create: POST /donations
            donations.read: GET /donations
            alerts.create: POST /alerts
            legacy.token: GET /legacy/token
            socket.token: GET /socket/token
            points.read: GET /points
            points.write: POST /points/subtract POST /points/import POST /points/add_to_all
            alerts.write:
              POST "/alerts/skip POST /alerts/mute_volume POST /alerts/unmute_volume
              POST /alerts/pause_queue POST /alerts/unpause_queue POST /alerts/send_test_alert"
            credits.write: POST /credits/roll
            profiles.write: GET /alert_profiles/get POST /alert_profiles/activate
            jar.write: POST /jar/empty
            wheel.write: POST /wheel/spin
            mediashare.control:
              PUT media-share/play-media PUT media-share/pause-media
              PUT media-share/volume-up PUT media-share/volume-down PUT media-share/skip-video
              PUT media-share/playback-video PUT media-share/enable-requests PUT media-share/disable-requests
              PUT media-share/enable-autoplay PUT media-share/disable-autoplay PUT
              media-share/enable-autoshow PUT media-share/disable-autoshow PUT media-share/enable-moderation
              PUT media-share/disable-moderation PUT media-share/enable-backup PUT
              media-share/disable-backup
          tokenUrl: /api/v1.0/token?grant_type=authorization_code
      type: oauth2
